### ISSUE TITLE
ToDo App

### ISSUE THREAD

**Issue by msteiner96** [wynd-answers/wynd-app#1]
- [x] Get map working
- [x] Add wallet to the app
- [x] Query state of DeFi placeholder
- [x] Query data from Data Platform
- [x] Pull it all together....
